// Code generated by mockery v2.53.4. DO NOT EDIT.

// Regenerate this file using `make store-mocks`.

package mocks

import (
	model "github.com/mattermost/mattermost/server/public/model"
	mock "github.com/stretchr/testify/mock"
)

// ChannelReadCursorStore is an autogenerated mock type for the ChannelReadCursorStore type
type ChannelReadCursorStore struct {
	mock.Mock
}

// Delete provides a mock function with given fields: channelId, userId
func (_m *ChannelReadCursorStore) Delete(channelId string, userId string) error {
	ret := _m.Called(channelId, userId)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(channelId, userId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteForChannel provides a mock function with given fields: channelId
func (_m *ChannelReadCursorStore) DeleteForChannel(channelId string) error {
	ret := _m.Called(channelId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteForChannel")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(channelId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteOldCursors provides a mock function with given fields: olderThan
func (_m *ChannelReadCursorStore) DeleteOldCursors(olderThan int64) error {
	ret := _m.Called(olderThan)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOldCursors")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int64) error); ok {
		r0 = rf(olderThan)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: channelId, userId
func (_m *ChannelReadCursorStore) Get(channelId string, userId string) (*model.ChannelReadCursor, error) {
	ret := _m.Called(channelId, userId)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *model.ChannelReadCursor
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*model.ChannelReadCursor, error)); ok {
		return rf(channelId, userId)
	}
	if rf, ok := ret.Get(0).(func(string, string) *model.ChannelReadCursor); ok {
		r0 = rf(channelId, userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ChannelReadCursor)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(channelId, userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetForChannel provides a mock function with given fields: channelId
func (_m *ChannelReadCursorStore) GetForChannel(channelId string) ([]*model.ChannelReadCursor, error) {
	ret := _m.Called(channelId)

	if len(ret) == 0 {
		panic("no return value specified for GetForChannel")
	}

	var r0 []*model.ChannelReadCursor
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]*model.ChannelReadCursor, error)); ok {
		return rf(channelId)
	}
	if rf, ok := ret.Get(0).(func(string) []*model.ChannelReadCursor); ok {
		r0 = rf(channelId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.ChannelReadCursor)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(channelId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetForUser provides a mock function with given fields: userId
func (_m *ChannelReadCursorStore) GetForUser(userId string) ([]*model.ChannelReadCursor, error) {
	ret := _m.Called(userId)

	if len(ret) == 0 {
		panic("no return value specified for GetForUser")
	}

	var r0 []*model.ChannelReadCursor
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]*model.ChannelReadCursor, error)); ok {
		return rf(userId)
	}
	if rf, ok := ret.Get(0).(func(string) []*model.ChannelReadCursor); ok {
		r0 = rf(userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.ChannelReadCursor)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Upsert provides a mock function with given fields: cursor
func (_m *ChannelReadCursorStore) Upsert(cursor *model.ChannelReadCursor) error {
	ret := _m.Called(cursor)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.ChannelReadCursor) error); ok {
		r0 = rf(cursor)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewChannelReadCursorStore creates a new instance of ChannelReadCursorStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewChannelReadCursorStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *ChannelReadCursorStore {
	mock := &ChannelReadCursorStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
